apiVersion: v1
kind: Service
metadata:
  name: tsm-agent-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: tsm-agent
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 5432
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: tsm-agent
