apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsm-agent-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: tsm-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
