apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsm-agent-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: tsm-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tsmAgent.postgres.volumeSize | quote }}
  {{- if .Values.tsmAgent.postgres.storageClass }}
  storageClassName: {{ .Values.tsmAgent.postgres.storageClass | quote }}
  {{- end }}