apiVersion: v1
kind: Secret
metadata:
  name: admin-auth
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: "password"
    secret-generator.v1.mittwald.de/length: "32"
stringData:
  username: {{ .Values.global.adminAccount.username | quote }}
