apiVersion: v1
kind: Secret
metadata:
  name: admin-auth
  labels:
    secret-generator.cs.sap.com/enabled: "true"
stringData:
  username: "admin"
  password: "%generate:password:length=32;num_symbols=1;symbols=_"
