apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-auth
  labels:
    secret-generator.cs.sap.com/enabled: "true"
stringData:
  username: "admin@isstech.io"
  password: "%generate:password:length=24"
