apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsm-agent-valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
      app.kubernetes.io/part-of: tsm-agent
      app.kubernetes.io/component: dictionary-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valkey
        app.kubernetes.io/part-of: tsm-agent
        app.kubernetes.io/component: dictionary-server
        external-egress: block
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always

      containers:
        - name: tsm-agent-valkey
          image: 'valkey/valkey:8'
          imagePullPolicy: Always
          command:
            - "/bin/bash"
          args:
            - "-c"
            - |
              [ -e /etc/valkey/auth/password ] && \
              create-acl.sh && \
              valkey-server /etc/valkey/valkey.conf
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: tsm-agent-valkey
              mountPath: "/data"
            - name: valkey-config
              mountPath: "/etc/valkey/valkey.conf"
              subPath: "valkey.conf"
            - name: valkey-config
              mountPath: "/usr/local/bin/create-acl.sh"
              subPath: "create-acl.sh"
            - name: tsm-agent-valkey-cert
              mountPath: "/etc/valkey/certs"
            - name: tsm-agent-valkey-auth
              mountPath: "/etc/valkey/auth"
            - name: issassist-ca-cert
              mountPath: "/etc/valkey/ca.crt"
              subPath: "tls.crt"
      volumes:
        - name: tsm-agent-valkey
          persistentVolumeClaim:
            claimName: tsm-agent-valkey
        - name: valkey-config
          configMap:
            name: valkey-config
            defaultMode: 0755
        - name: tsm-agent-valkey-cert
          secret:
            secretName: tsm-agent-valkey-cert
        - name: tsm-agent-valkey-auth
          secret:
            secretName: tsm-agent-valkey-auth
        - name: issassist-ca-cert
          secret:
            secretName: issassist-ca-cert
