apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsm-agent-valkey
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: tsm-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tsmAgent.valkey.volumeSize | quote }}
  {{- if .Values.tsmAgent.valkey.storageClass }}
  storageClassName: {{ .Values.tsmAgent.valkey.storageClass | quote }}
  {{- end }}
