apiVersion: v1
kind: Service
metadata:
  name: tsm-agent-valkey
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: tsm-agent
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      nodePort: 30104
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: tsm-agent
