apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-valkey-data
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
