apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-valkey
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.api.valkey.volumeSize | quote }}
  {{- if .Values.api.valkey.storageClass }}
  storageClassName: {{ .Values.api.valkey.storageClass | quote }}
  {{- end }}
