apiVersion: v1
kind: Service
metadata:
  name: api-valkey
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      nodePort: 30102
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: api
