apiVersion: v1
kind: Service
metadata:
  name: tsm-agent
  labels:
    app.kubernetes.io/name: tsm-agent
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 50051
      nodePort: 30106
  selector:
    app.kubernetes.io/name: tsm-agent
