apiVersion: batch/v1
kind: Job
metadata:
  name: "initial-tsm-client-build"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "initial-tsm-client-build"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: tsm-client-builder
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=git://github.com/IssTech/tsm-client-docker.git"
            - "--destination=registry:5000/tsm-client:latest"
            - "--insecure-registry=registry:5000"
