apiVersion: v1
kind: Pod
metadata:
  name: tsm-client-builder
spec:
  containers:
    - name: tsm-client-builder
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--context=git://github.com/IssTech/tsm-client-docker.git"
        - "--destination=registry:5000/tsm-client:latest"
        - "--insecure-registry=registry:5000"
  restartPolicy: Never
