apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsm-agent
secrets:
  - name: issassist-ca-cert
  - name: tsm-agent-cert
  - name: tsm-agent-postgres-auth
  - name: tsm-agent-valkey-auth
  - name: messaging-cert
imagePullSecrets:
  - name: isstech-repository-auth
