apiVersion: v1
kind: Service
metadata:
  name: api-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30101
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: api
