apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
