apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.api.postgres.volumeSize | quote }}
  {{- if .Values.api.postgres.storageClass }}
  storageClassName: {{ .Values.api.postgres.storageClass | quote }}
  {{- end }}
