apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  PGADMIN_DEFAULT_PASSWORD_FILE: "/etc/pgadmin/auth/password"
  # PGADMIN_ENABLE_TLS: "True"
  PGADMIN_LISTEN_PORT: "5050"
  PGADMIN_CONFIG_SHOW_GRAVATAR_IMAGE: "False"
  PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
  PGADMIN_CONFIG_SESSION_COOKIE_SAMESITE: "'None'"
  PGADMIN_CONFIG_SESSION_COOKIE_SECURE: "True"
  PGADMIN_CONFIG_SESSION_COOKIE_HTTPONLY: "False"
  SCRIPT_NAME: "/pgadmin"
