apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app.kubernetes.io/name: pgadmin
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5050
      nodePort: 30100
  selector:
    app.kubernetes.io/name: pgadmin
