{{ if .Values.pgAdmin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  annotations:
    # Traefik: Allow up to 2GB upload size
    traefik.http.middlewares.limit.buffering.maxRequestBodyBytes: "2000000000"
    # Nginx: Allow up to 2GB upload size
    nginx.ingress.kubernetes.io/proxy-body-size: "2g"
  {{ if eq .Values.global.ingress.tls.issuerType "cluster" }}
    cert-manager.io/cluster-issuer: {{ .Values.global.ingress.tls.issuer }}
  {{ else if eq .Values.global.ingress.tls.issuerType "issuer" }}
    cert-manager.io/issuer: {{ .Values.global.ingress.tls.issuer }}
  {{ end }}
  {{- range $key, $value := .Values.pgAdmin.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}

spec:
  ingressClassName: {{ .Values.global.ingress.ingressClass }}
  rules:
    - host: {{ .Values.global.publicDomainName }}
      http:
        paths:
        - pathType: Prefix
          path: "{{ .Values.global.basePath }}/pgadmin"
          backend:
            service:
              name: pgadmin
              port:
                number: 5050
  tls:
    - hosts:
        - {{ .Values.global.publicDomainName }}
      secretName: {{ if eq .Values.global.ingress.tls.issuerType "disabled" }}
        self-signed-ingress-cert
      {{ else }}
        ingress-cert
      {{ end }}
{{ end }}