{{ if .Values.pgAdmin.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{ end }}
