apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app.kubernetes.io/name: pgadmin
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5050
  selector:
    app.kubernetes.io/name: pgadmin
