apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-postgres-cert
spec:
  commonName: api-postgres
  secretName: api-postgres-cert
  duration: {{ .Values.global.certDuration }}
  renewBefore: 72h
  usages:
    - client auth
    - server auth
    - key encipherment
    - digital signature
    - data encipherment
  dnsNames:
    - "api-postgres"
    - "localhost"
  subject:
    organizations:
      - "IssTech AB"
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: issassist-ca-issuer
    kind: Issuer
    group: cert-manager.io
