apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
spec:
  commonName: api
  secretName: api-cert
  duration: {{ .Values.global.certDuration }}
  renewBefore: 72h
  subject:
    organizations:
      - "IssTech AB"
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: issassist-ca-issuer
    kind: Issuer
    group: cert-manager.io
