# TSM Agent Messaging certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: messaging
spec:
  commonName: messaging
  secretName: messaging-cert
  duration: {{ .Values.global.caCertDuration }}
  renewBefore: 360h  # 15 days
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
