# TSM Agent Messaging certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: messaging
spec:
  commonName: messaging
  secretName: messaging-cert
  duration: {{ .Values.global.caCertDuration }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
