apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tsm-agent-cert
spec:
  commonName: tsm-agent
  secretName: tsm-agent-cert
  duration: {{ .Values.global.certDuration }}
  renewBefore: 72h
  usages:
    - client auth
    - server auth
    - key encipherment
    - digital signature
    - data encipherment
  dnsNames:
    - "tsm-agent"
    - "localhost"
  subject:
    organizations:
      - "IssTech AB"
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: issassist-ca-issuer
    kind: Issuer
    group: cert-manager.io
