{{ if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
       app.kubernetes.io/name: api
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: isstech-repository-auth

      containers:
        - name: api
          image: {{ .Values.api.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: "{{ .Values.global.basePath }}/api/v1/info/"
            initialDelaySeconds: 30
            timeoutSeconds: 60
          env:
            - name: IA_ROOT_PATH
              value: "{{ .Values.global.basePath }}/api"
            - name: IA_FORWARDED_ALLOW_IPS
              value: "*"
            - name: IA_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-postgres-auth
                  key: "username"
            - name: IA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-postgres-auth
                  key: "password"
            - name: IA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-valkey-auth
                  key: "password"
            - name: IA_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: admin-auth
                  key: "username"
            - name: IA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-auth
                  key: "password"
            - name: IA_ADMIN_EMAIL
              value: {{ .Values.global.adminAccount.email | quote }}
            - name: IA_ADMIN_TZ
              value: {{ .Values.global.adminAccount.timezone | quote }}
            - name: IA_ADMIN_PASSWORD_IS_LOCKED
              value: {{ .Values.global.adminAccount.lockPassword | quote }}
            - name: IA_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-jwt-secret-key
                  key: "jwt-secret-key"
            {{if .Values.global.mail.smtpHost }}
            - name: IA_SMTP_HOST
              value: {{ .Values.global.mail.smtpHost | quote }}
            {{end}}
            {{if .Values.global.mail.smtpPort }}
            - name: IA_SMTP_PORT
              value: {{ .Values.global.mail.smtpPort | quote }}
            {{end}}
            {{if .Values.global.mail.smtpTLS }}
            - name: IA_SMTP_TLS
              value: {{ .Values.global.mail.smtpTLS | quote }}
            {{end}}
            {{if .Values.global.mail.fromEmailAddress }}
            - name: IA_MAIL_FROM_EMAIL_ADDRESS
              value: {{ .Values.global.mail.fromEmailAddress | quote }}
            {{end}}
            {{if .Values.global.mail.fromName }}
            - name: IA_MAIL_FROM_NAME
              value: {{ .Values.global.mail.fromName | quote }}
            {{end}}
            - name: IA_SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp-auth
                  key: "username"
            - name: IA_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-auth
                  key: "password"
            - name: IA_CORS_ALLOWED_ORIGINS
              value: '"{{- template "webGUIOrigin" . }}"'
          volumeMounts:
            - name: api-config
              mountPath: "/app/data/config.toml"
              subPath: "config.toml"
      volumes:
        - name: api-config
          configMap:
            name: api-config
        - name: api-postgres-auth
          secret:
            secretName: api-postgres-auth
        - name: api-valkey-auth
          secret:
            secretName: api-valkey-auth
        - name: admin-auth
          secret:
            secretName: admin-auth
        - name: api-jwt-secret-key
          secret:
            secretName: api-jwt-secret-key
        - name: smtp-auth
          secret:
            secretName: smtp-auth
{{ end }}
