apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30107
  selector:
    app.kubernetes.io/name: api
