apiVersion: v1
kind: Secret
metadata:
  name: api-jwt-secret-key
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: "jwt-secret-key"
    secret-generator.v1.mittwald.de/length: "64"
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-auth
stringData:
  username: {{ .Values.api.mail.smtpUsername | quote }}
  password: {{ .Values.api.mail.smtpPassword | quote }}
