apiVersion: v1
kind: Secret
metadata:
  name: api-jwt-secret-key
  labels:
    secret-generator.cs.sap.com/enabled: "true"
stringData:
  jwt-secret-key: "%generate:password:length=64;num_symbols=1;symbols=_"

---

apiVersion: v1
kind: Secret
metadata:
  name: smtp-auth
  labels:
    secret-generator.cs.sap.com/enabled: "true"
stringData:
  username: {{ .Values.api.mail.smtpUsername | quote }}
  password: {{ .Values.api.mail.smtpPassword | quote }}
