apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sp-restore-tester
rules:
- apiGroups: ["", "apps"]
  resources:
    - "deployments"
    - "pods"
    - "pods/log"
    - "pods/exec"
    - "persistentvolumeclaims"
    - "persistentvolumes"
    - "configmaps"
  verbs:
    - "*"
