apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: issassist-ingress
  annotations:
  {{ if eq .Values.global.ingress.tls.issuerType "cluster" }}
    cert-manager.io/cluster-issuer: {{ .Values.global.ingress.tls.issuer }}
  {{ else if eq .Values.global.ingress.tls.issuerType "issuer" }}
    cert-manager.io/issuer: {{ .Values.global.ingress.tls.issuer }}
  {{ else if eq .Values.global.ingress.tls.issuerType "disabled" }}
    {}
  {{ end }}

spec:
  ingressClassName: {{ .Values.global.ingress.ingressClass }}
  rules:
  - host: {{ .Values.global.publicDomainName }}
    http:
      paths:
      - pathType: Prefix
        {{ if .Values.global.basePath }}
        path: "{{ .Values.global.basePath }}"
        {{ else }}
        path: "/"
        {{ end }}
        backend:
          service:
            name: webgui
            port:
              number: 8000
  - host: {{ .Values.global.publicDomainName }}
    http:
      paths:
      - pathType: Prefix
        path: "{{ .Values.global.basePath }}/api/v1"
        backend:
          service:
            name: api
            port:
              number: 8000
  tls:
    - hosts:
        - {{ .Values.global.publicDomainName }}
      secretName: {{ if eq .Values.global.ingress.tls.issuerType "disabled" }}
        self-signed-ingress-cert
      {{ else }}
        ingress-cert
      {{ end }}
