{{- if .Values.superset.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-valkey
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: superset
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.superset.valkey.volumeSize | quote }}
  {{- if .Values.superset.valkey.storageClass }}
  storageClassName: {{ .Values.superset.valkey.storageClass | quote }}
  {{- end }}
{{- end }}