{{- if .Values.superset.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: superset
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: superset
        app.kubernetes.io/component: database
        external-egress: block
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always

      containers:
        - name: superset-postgres
          image: 'postgres:18'
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: "PGDATA"
              value: "/var/lib/postgresql/data/db"
            - name: "POSTGRES_DB"
              value: "superset"
            - name: "POSTGRES_USER_FILE"
              value: "/etc/postgresql/auth/username"
            - name: "POSTGRES_PASSWORD_FILE"
              value: "/etc/postgresql/auth/password"
          volumeMounts:
            - name: superset-postgres
              mountPath: "/var/lib/postgresql/data"
            - name: superset-env
              mountPath: "/etc/postgresql/auth"
      volumes:
        - name: superset-postgres
          persistentVolumeClaim:
            claimName: superset-postgres
        - name: superset-env
          secret:
            secretName: superset-env
            items:
              - key: DB_USER
                path: username
              - key: DB_PASS
                path: password
{{- end }}